apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backendapi
  namespace: qa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: qa.localhost.com
    http:
      paths:
      - pathType: Prefix
        path: "/config"
        backend:
          service:
            name: gf-config-service
            port:
              number: 5000