apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backendapi
  namespace: qa
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: qa.localhost.com
    http:
      paths:
      - path: "/config/(.*)"
        pathType: Prefix
        backend:
          service:
            name: gf-config-service
            port:
              number: 80