apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gf-config-configmap
  namespace: prod
data:
  ENV: qa
  SERVICE: gf-config
  VALT_USER: respect
  VALT_PASS: respect@123
  VALT_PATH: /bin/application
---
apiVersion: v1
kind: Service
metadata:
  name: gf-config-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: gf-config
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gf-config-deployment
  namespace: prod
  labels:
    app: gf-config
  annotations:
    rollout: ""
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gf-config
  template:
    metadata:
      labels:
        app: gf-config
    spec:
      containers:
        - name: golang
          image: mucunga90/gf-config:prod
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: gf-config-configmap
          volumeMounts:
            - name: dotenv
              mountPath: ./.env
              subPath: .env
              readOnly: true
      volumes:
        - name: dotenv
          secret:
            secretName: gf-config-secret
            items:
              - key: .env
                path: ./.env