apiVersion: v1
kind: Namespace
metadata:
  name: qa
---
apiVersion: v1
kind: Ingress
metadata:
  name: ingress
  namespace: qa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: gf-config-service
    servicePort: 80
  rules:
  - host: qa
    http:
      paths:
      - path: /config
        backend:
          serviceName: gf-config-service
          servicePort: 80
      - path: /config
        backend:
          serviceName: gf-config-service
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gf-config-configmap
  namespace: qa
data:
  ENV: qa
  ADR: :5000
---
apiVersion: v1
kind: Service
metadata:
  name: gf-config-service
  namespace: qa
spec:
  type: ClusterIP
  selector:
    app: gf-config
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gf-config-deployment
  namespace: qa
  labels:
    app: gf-config
  annotations:
    rollout: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gf-config
  template:
    metadata:
      labels:
        app: gf-config
    spec:
      containers:
        - name: golang
          image: mucunga90/gf-config:qa
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: gf-config-configmap
          volumeMounts:
            - name: dotenv
              mountPath: ./.env
              subPath: .env
              readOnly: true
      volumes:
        - name: dotenv
          secret:
            secretName: gf-config-secret
            items:
              - key: .env
                path: ./.env