apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qa-ingress
  namespace: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: qa.localhost.com
    http:
      paths:
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: gf-user-service
            port:
              number: 80
  tls: 
  - hosts: 
      - qa.localhost.com
    secretName: tls-secret