apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stage-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: stage.localhost.com
    http:
      paths:
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: gf-user-service
            port:
              number: 5000
  tls: 
  - hosts: 
      - stage.localhost.com
    secretName: tls-secret