@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Get Config
# @name GetConfig
POST http://{{host}}/config/vault
Content-Type: {{contentType}}

{
    "service": "gf-notify",
    "env": "qa",
    "vaultUser": "user",
    "vaultPass": "pass"
}