@hostname = 127.0.0.1
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Get Config
# @name GetConfig
POST https://{{host}}/config/vault
Content-Type: {{contentType}}

{
    "impl": "gf-notify",
    "application": "respect",
    "env": "prod",
    "user": "respect",
    "pass": "elders@2020"
}