# Trigger the workflow to deploy to qa environment only when:
# - an existing pull request with any name/type is merged to the main or develop branch
# - a commit is directly pushed to the main or develop branch
  
name: Continuous deployment
  
on:
  push:
    branches:
      - main
      - develop
  
jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.vars.outputs.repo }}
      commit: ${{ steps.vars.outputs.commit }}
    steps:
      - name: Use repository
        uses: actions/checkout@v2
      - name: Build variables
        id: vars
        run: |
          echo "::set-output name=repo::$GITHUB_REPOSITORY"
          echo "::set-output name=commit::$(git rev-parse --short "$GITHUB_SHA")"
      - name: Upload repository
        uses: actions/upload-artifact@v2
        with:
          name: repository
          path: |
            ${{ github.workspace }}/deploy

  deploy:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v2
        with:
          name: repository
      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
          curl -LO "https://dl.k8s.io/v1.22.0/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBE_QA_URL }}" > $HOME/.kube/config
          echo "${{ secrets.KUBE_QA_CONFIG }}" > $HOME/.kube/qa.yaml
      - name: Deploy
        run: |
          kubectl --kubeconfig $HOME/.kube/config delete secret -n qa gf-config-secret
          kubectl --kubeconfig $HOME/.kube/config create secret generic -n qa gf-config-secret --from-env-file=$HOME/.kube/qa.yaml